# Generated by Django 2.2.4 on 2019-09-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronLogic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charpairing',
            name='corrAudio',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
    ]
