# Generated by Django 2.2.4 on 2019-09-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronLogic', '0002_charpairing_corraudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charpairing',
            name='corrAudio',
            field=models.FileField(default='default', upload_to=''),
        ),
    ]
